services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: criterium-postgres
    env_file:
      - apps/api/.env.production
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-criterium}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/var/www/criterium/postgres/pg:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - criterium-network

  # Backend API Service
  backend:
    image: ghcr.io/mdportnov/criterium-backend:latest
    container_name: criterium-backend
    env_file:
      - apps/api/.env.production
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      BACKEND_PORT: ${BACKEND_PORT:-3000}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    restart: always
    networks:
      - criterium-network

  # Frontend Web Service
  frontend:
    image: ghcr.io/mdportnov/criterium-frontend:latest
    container_name: criterium-frontend
    env_file:
      - apps/web/.env.production
    ports:
      - "80:80"
    restart: always
    networks:
      - criterium-network

networks:
  criterium-network:
    driver: bridge
    attachable: true