name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'libs/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: criterium-edu-frontend
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: frontend.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Copy compose.yml files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: criterium.digital.mephi.ru
          port: 2250
          username: ubuntu
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "compose.yml,.env.example"
          target: "~/criterium/"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: criterium.digital.mephi.ru
          port: 2250
          username: ubuntu
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/criterium
            sudo chown -R ubuntu:ubuntu /var/www/criterium
            
            cp -f ~/criterium/compose.yml /var/www/criterium/
            cp -f ~/criterium/.env.example /var/www/criterium/
            
            cd /var/www/criterium
            
            mkdir -p ./data/pg
            chmod -R 777 ./data
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker compose pull
            docker compose up -d frontend
            docker system prune -af